//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Communications.Contacts.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Communications.Contacts.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;c:contact c:Version=&quot;1&quot;
        ///           xmlns:c=&quot;http://schemas.microsoft.com/Contact&quot;
        ///           xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///           xmlns:extensiontest=&quot;http://schemas.microsoft.com/Contact/Extended/extensiontest&quot; 
        ///           xmlns:extension2=&quot;http://schemas.microsoft.com/Contact/Extended/extension2&quot; 
        ///           xmlns:mytestextension=&quot;http://schemas.microsoft.com/Contact/Extended/mytestextension&quot; 
        ///           xmlns:msn=&quot;http://msn.com/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alexei_Karamazov {
            get {
                return ResourceManager.GetString("Alexei_Karamazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcarusFalling {
            get {
                object obj = ResourceManager.GetObject("IcarusFalling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;c:contact c:Version=&quot;1&quot; xmlns:c=&quot;http://schemas.microsoft.com/Contact&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:MSP2P=&quot;http://schemas.microsoft.com/Contact/Extended/MSP2P&quot; xmlns:MSWABMAPI=&quot;http://schemas.microsoft.com/Contact/Extended/MSWABMAPI&quot;&gt;
        ///	&lt;c:CreationDate&gt;2007-05-28T22:51:43Z&lt;/c:CreationDate&gt;&lt;c:Extended&gt;&lt;MSWABMAPI:PropTag0x80091102 c:ContentType=&quot;binary/x-ms-wab-mapi&quot; c:type=&quot;binary&quot; c:Version=&quot;5&quot; c:ModificationDate=&quot;2007-05-29T00:02:12Z&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapiGroup {
            get {
                return ResourceManager.GetString("MapiGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsLiveJewel {
            get {
                object obj = ResourceManager.GetObject("WindowsLiveJewel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
